%YAML:1.0
---
#保存设置
isSave: 0     #是否保存
saveStartNum: 0   #保存图片的初始编号
img_savePath: ../data/

#输出FPS
out_fps: 120

#需要打击的颜色
color2Strike: 0 # 0蓝，1红


#中心区域面积限制 100 * 400 * 0.75 * 0.75
center_area_of_contours_lower: 100
center_area_of_contours_upper: 500

#装甲板区域面积限制 2000 * 5000 * 0.75 * 0.75
armor_area_of_contours_lower: 1400
armor_area_of_contours_upper: 4500
armor_area_of_contours_max: 7000

armor_length_of_contours_low: 300
armor_length_of_contours_max: 800

#中心区域长宽比限制
center_rect_div_limit: 0.75

#装甲板区域长宽比限制
armor_rect_div_limit: 0.4


#中心点距离图像边界限制 190 *0.75
roi_size: 190

#中心圆与装甲板中心距离限制 170  200 *0.75
distance_lower:  100
distance_upper:  200

#预测增加角度
predict_angle: 20

#预测重力补偿
predict_gravity_x: -17
predict_gravity_y: -45

#判断顺逆时针间隔帧数
clock_wise_frame: 20

#SVM路径
svm_model_path: ../Config/Models/cubot_svm_4_30_dafu.xml
